//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai2_Nhom7_LTWIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int AppID { get; set; }
        public int JobID { get; set; }
        public int CvID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
