//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai2_Nhom7_LTWIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public int Id { get; set; }
        public int CanID { get; set; }
        public string Title { get; set; }
        public string Introduce { get; set; }
        public string Education { get; set; }
        public string Exp { get; set; }
        public string Skills { get; set; }
        public string Certificate { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
