//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai2_Nhom7_LTWIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Require { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Location { get; set; }
        public int EmpID { get; set; }
        public System.DateTime LastDate { get; set; }
        public string TimeWork { get; set; }
        public string Benefit { get; set; }
        public string HowApply { get; set; }
        public string ReqExperience { get; set; }
        public string Education { get; set; }
        public string Type { get; set; }
    }
}
